from controllers.directory_controller import directory_controller
from controllers.player_controller import player_controller
from controllers.library_controller import library_controller
from controllers.queue_controller import queue_controller

print("Voici les répertoires: ")
for directory in library_controller.directories:
    print(directory.id,directory.path)
print("Voici les morceaux: ")
print(library_controller.songs)
print("Voici la file d'attente: ")
print(library_controller.queue)
print("Voici le morceau en cours de lecture:")
print(player_controller.player_status())
print("Je lance la lecture")
player_controller.play_song()
input("...Appuyer pour mettre en pause")
player_controller.play_song()
input("Appuyer pour relancer la lecture")
player_controller.play_song()
input("Appuyer pour nexter")
player_controller.next_song()
input("Appuyer pour arreter le chanson")
player_controller.stop_play()
print(player_controller.player_status())
print("Je change le mode de répetition")
print(player_controller.change_repeat_mode())
print(player_controller.player_status())
print("Je change le mode de répetition")
print(player_controller.change_repeat_mode())
print(player_controller.player_status())
print("Je change le mode de répetition")
print(player_controller.change_repeat_mode())
print(player_controller.player_status())
queue_controller.move_song(86,2,0)
queue_controller.clear_queue()
print("Fin")